### ISSUE TITLE
eschema syntax highlight crashes in atom-1.22

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb-editor-plugin#8]
### Steps to reproduce:

1. Open any *.eschema file in atom-1.22.0

**Atom**: 1.22.0 x64
**dev-libs/oniguruma**: 6.6.1
**Electron**: 1.6.15
**OS**: linux 4.14.0-rc8-00016-g64ba914f196d
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: invalid pattern in look-behind

```
At /usr/lib64/atom/app.asar/node_modules/first-mate/lib/scanner.js:31

Error: invalid pattern in look-behind
    at Scanner.module.exports.Scanner.createScanner (/app.asar/node_modules/first-mate/lib/scanner.js:31:24)
    at Scanner.module.exports.Scanner.getScanner (/app.asar/node_modules/first-mate/lib/scanner.js:37:31)
    at Scanner.module.exports.Scanner.findNextMatch (/app.asar/node_modules/first-mate/lib/scanner.js:56:22)
    at Rule.module.exports.Rule.findNextMatch (/app.asar/node_modules/first-mate/lib/rule.js:98:28)
    at Rule.module.exports.Rule.getNextTags (/app.asar/node_modules/first-mate/lib/rule.js:154:21)
    at Grammar.module.exports.Grammar.tokenizeLine (/app.asar/node_modules/first-mate/lib/grammar.js:152:44)
    at TokenizedBuffer.buildTokenizedLineForRowWithText (/app.asar/src/tokenized-buffer.js:506:44)
    at TokenizedBuffer.buildTokenizedLineForRow (/app.asar/src/tokenized-buffer.js:501:17)
    at TokenizedBuffer.tokenizeNextChunk (/app.asar/src/tokenized-buffer.js:389:41)
    at _.defer (/app.asar/src/tokenized-buffer.js:373:57)
    at /app.asar/node_modules/underscore/underscore.js:666:47
```

**Comment by 1st1** [comment]
I guess this can be closed now.
